In [9]:
import tensorflow as tf
import numpy as np

In [10]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [11]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [12]:
xy = MinMaxScaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [13]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]


In [14]:
X = tf.placeholder(tf.float32,shape=[None,4])
Y = tf.placeholder(tf.float32,shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]),name = 'bias')

hypothesis = tf.matmul(X,W)+b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost,hypothesis, train],feed_dict={X:x_data,Y:y_data})
    print(step,"Cost:",cost_val, "\nPrediction:\n",hy_val)

0 Cost: 0.39572728 
Prediction:
 [[-0.35649467]
 [ 0.34678692]
 [ 0.38315028]
 [ 0.35662705]
 [ 0.37456903]
 [ 0.4208614 ]
 [ 0.78029823]
 [ 0.8001259 ]]
1 Cost: 0.3349762 
Prediction:
 [[-0.19355297]
 [ 0.47291586]
 [ 0.48557532]
 [ 0.43213192]
 [ 0.47002348]
 [ 0.5106796 ]
 [ 0.81998414]
 [ 0.82908905]]
2 Cost: 0.3002553 
Prediction:
 [[-0.08107805]
 [ 0.5511334 ]
 [ 0.54808104]
 [ 0.4767442 ]
 [ 0.5287733 ]
 [ 0.56510985]
 [ 0.8364759 ]
 [ 0.83558595]]
3 Cost: 0.2762116 
Prediction:
 [[-1.7452240e-04]
 [ 5.9976804e-01]
 [ 5.8596009e-01]
 [ 5.0233066e-01]
 [ 5.6485474e-01]
 [ 5.9771311e-01]
 [ 8.3889550e-01]
 [ 8.2858312e-01]]
4 Cost: 0.25693905 
Prediction:
 [[0.06084234]
 [0.6301402 ]
 [0.60865754]
 [0.5162195 ]
 [0.5869374 ]
 [0.6168647 ]
 [0.8328691 ]
 [0.8136064 ]]
5 Cost: 0.24013901 
Prediction:
 [[0.10920274]
 [0.64924175]
 [0.62200636]
 [0.5229356 ]
 [0.6003767 ]
 [0.6277369 ]
 [0.82186383]
 [0.79405683]]
6 Cost: 0.2248922 
Prediction:
 [[0.1493851 ]
 [0.66139066]
 [0.6296084

201 Cost: 0.0055236397 
Prediction:
 [[ 0.96881866]
 [ 0.80536366]
 [ 0.618173  ]
 [ 0.33937114]
 [ 0.5878278 ]
 [ 0.55611724]
 [ 0.1932643 ]
 [-0.02171619]]
202 Cost: 0.0055219256 
Prediction:
 [[ 0.9688159 ]
 [ 0.8055236 ]
 [ 0.6182077 ]
 [ 0.33928168]
 [ 0.5877874 ]
 [ 0.55608445]
 [ 0.19313544]
 [-0.02173355]]
203 Cost: 0.005520233 
Prediction:
 [[ 0.96881264]
 [ 0.80568135]
 [ 0.61824197]
 [ 0.33919358]
 [ 0.5877473 ]
 [ 0.5560521 ]
 [ 0.19300862]
 [-0.02174959]]
204 Cost: 0.0055185696 
Prediction:
 [[ 0.9688089 ]
 [ 0.80583686]
 [ 0.6182755 ]
 [ 0.33910698]
 [ 0.58770764]
 [ 0.5560202 ]
 [ 0.19288386]
 [-0.02176438]]
205 Cost: 0.0055169314 
Prediction:
 [[ 0.96880466]
 [ 0.80599004]
 [ 0.61830866]
 [ 0.33902162]
 [ 0.58766836]
 [ 0.5559887 ]
 [ 0.19276108]
 [-0.02177793]]
206 Cost: 0.005515311 
Prediction:
 [[ 0.9687999 ]
 [ 0.8061411 ]
 [ 0.6183412 ]
 [ 0.3389377 ]
 [ 0.5876293 ]
 [ 0.5559577 ]
 [ 0.19264024]
 [-0.0217903 ]]
207 Cost: 0.005513725 
Prediction:
 [[ 0.9687949 ]
 [ 

406 Cost: 0.0053346115 
Prediction:
 [[ 0.96895254]
 [ 0.81564116]
 [ 0.6197918 ]
 [ 0.33411518]
 [ 0.5835687 ]
 [ 0.55344725]
 [ 0.18352988]
 [-0.01818892]]
407 Cost: 0.005333893 
Prediction:
 [[ 0.9689615 ]
 [ 0.8156472 ]
 [ 0.6197886 ]
 [ 0.33411404]
 [ 0.58355606]
 [ 0.55344135]
 [ 0.1835106 ]
 [-0.01816615]]
408 Cost: 0.005333177 
Prediction:
 [[ 0.96897095]
 [ 0.81565326]
 [ 0.6197856 ]
 [ 0.334113  ]
 [ 0.58354366]
 [ 0.55343556]
 [ 0.18349144]
 [-0.01814336]]
409 Cost: 0.00533246 
Prediction:
 [[ 0.9689802 ]
 [ 0.8156592 ]
 [ 0.61978245]
 [ 0.3341121 ]
 [ 0.5835312 ]
 [ 0.55342984]
 [ 0.1834723 ]
 [-0.01812058]]
410 Cost: 0.005331747 
Prediction:
 [[ 0.96898955]
 [ 0.815665  ]
 [ 0.6197792 ]
 [ 0.33411118]
 [ 0.5835188 ]
 [ 0.55342406]
 [ 0.18345325]
 [-0.01809783]]
411 Cost: 0.00533103 
Prediction:
 [[ 0.96899885]
 [ 0.81567067]
 [ 0.61977607]
 [ 0.3341104 ]
 [ 0.5835064 ]
 [ 0.5534183 ]
 [ 0.1834343 ]
 [-0.01807509]]
412 Cost: 0.005330313 
Prediction:
 [[ 0.96900827]
 [ 0.815

 [-0.01313108]]
644 Cost: 0.005178244 
Prediction:
 [[ 0.9714022 ]
 [ 0.81573534]
 [ 0.61879677]
 [ 0.3346603 ]
 [ 0.58101666]
 [ 0.5522418 ]
 [ 0.17995343]
 [-0.0131113 ]]
645 Cost: 0.0051776464 
Prediction:
 [[ 0.9714124 ]
 [ 0.81573385]
 [ 0.6187924 ]
 [ 0.33466387]
 [ 0.5810071 ]
 [ 0.552237  ]
 [ 0.17994046]
 [-0.01309155]]
646 Cost: 0.005177039 
Prediction:
 [[ 0.97142243]
 [ 0.8157324 ]
 [ 0.61878824]
 [ 0.33466744]
 [ 0.5809974 ]
 [ 0.552232  ]
 [ 0.17992754]
 [-0.0130718 ]]
647 Cost: 0.005176436 
Prediction:
 [[ 0.97143245]
 [ 0.81573087]
 [ 0.61878383]
 [ 0.33467102]
 [ 0.58098775]
 [ 0.55222696]
 [ 0.17991461]
 [-0.01305206]]
648 Cost: 0.0051758373 
Prediction:
 [[ 0.97144264]
 [ 0.81572944]
 [ 0.6187797 ]
 [ 0.3346746 ]
 [ 0.5809782 ]
 [ 0.5522222 ]
 [ 0.17990172]
 [-0.01303232]]
649 Cost: 0.0051752343 
Prediction:
 [[ 0.9714528 ]
 [ 0.81572795]
 [ 0.61877555]
 [ 0.33467823]
 [ 0.5809686 ]
 [ 0.5522173 ]
 [ 0.17988884]
 [-0.01301261]]
650 Cost: 0.0051746345 
Prediction:
 [[

899 Cost: 0.0050363075 
Prediction:
 [[ 0.9737926 ]
 [ 0.8153672 ]
 [ 0.61782295]
 [ 0.33564255]
 [ 0.57875353]
 [ 0.55095774]
 [ 0.1769227 ]
 [-0.00846779]]
900 Cost: 0.0050357925 
Prediction:
 [[ 0.9738012 ]
 [ 0.8153659 ]
 [ 0.61781967]
 [ 0.33564654]
 [ 0.5787453 ]
 [ 0.5509526 ]
 [ 0.17691174]
 [-0.00845108]]
901 Cost: 0.0050352784 
Prediction:
 [[ 0.9738099 ]
 [ 0.81536466]
 [ 0.6178162 ]
 [ 0.33565062]
 [ 0.57873714]
 [ 0.5509475 ]
 [ 0.17690079]
 [-0.00843437]]
902 Cost: 0.0050347624 
Prediction:
 [[ 0.97381854]
 [ 0.8153632 ]
 [ 0.6178128 ]
 [ 0.33565468]
 [ 0.5787289 ]
 [ 0.55094224]
 [ 0.17688984]
 [-0.00841768]]
903 Cost: 0.005034253 
Prediction:
 [[ 0.973827  ]
 [ 0.81536204]
 [ 0.61780936]
 [ 0.3356587 ]
 [ 0.5787208 ]
 [ 0.55093706]
 [ 0.17687887]
 [-0.008401  ]]
904 Cost: 0.005033737 
Prediction:
 [[ 0.9738355 ]
 [ 0.81536067]
 [ 0.617806  ]
 [ 0.33566275]
 [ 0.5787126 ]
 [ 0.5509318 ]
 [ 0.17686796]
 [-0.00838432]]
905 Cost: 0.0050332216 
Prediction:
 [[ 0.97384423]
 [

1197 Cost: 0.0048948843 
Prediction:
 [[ 0.9761217 ]
 [ 0.8150375 ]
 [ 0.61694986]
 [ 0.33689317]
 [ 0.57652134]
 [ 0.54937655]
 [ 0.173931  ]
 [-0.00393912]]
1198 Cost: 0.004894446 
Prediction:
 [[ 0.9761288 ]
 [ 0.81503654]
 [ 0.6169473 ]
 [ 0.3368975 ]
 [ 0.5765145 ]
 [ 0.5493711 ]
 [ 0.17392184]
 [-0.00392535]]
1199 Cost: 0.0048940065 
Prediction:
 [[ 0.97613585]
 [ 0.8150356 ]
 [ 0.6169449 ]
 [ 0.33690187]
 [ 0.5765077 ]
 [ 0.5493657 ]
 [ 0.17391269]
 [-0.00391159]]
1200 Cost: 0.0048935656 
Prediction:
 [[ 0.9761429 ]
 [ 0.81503475]
 [ 0.6169424 ]
 [ 0.33690625]
 [ 0.57650083]
 [ 0.5493603 ]
 [ 0.17390352]
 [-0.00389784]]
1201 Cost: 0.004893127 
Prediction:
 [[ 0.97614986]
 [ 0.81503385]
 [ 0.61693996]
 [ 0.33691058]
 [ 0.576494  ]
 [ 0.54935485]
 [ 0.17389438]
 [-0.0038841 ]]
1202 Cost: 0.0048926915 
Prediction:
 [[ 0.9761569 ]
 [ 0.81503296]
 [ 0.61693734]
 [ 0.33691493]
 [ 0.5764872 ]
 [ 0.5493495 ]
 [ 0.1738852 ]
 [-0.00387037]]
1203 Cost: 0.004892252 
Prediction:
 [[ 0.976164

1405 Cost: 0.004807848 
Prediction:
 [[ 0.97749484]
 [ 0.814871  ]
 [ 0.61648417]
 [ 0.33781195]
 [ 0.57518303]
 [ 0.5482325 ]
 [ 0.17213282]
 [-0.0012597 ]]
1406 Cost: 0.004807447 
Prediction:
 [[ 0.97750115]
 [ 0.8148704 ]
 [ 0.61648226]
 [ 0.3378165 ]
 [ 0.575177  ]
 [ 0.548227  ]
 [ 0.1721247 ]
 [-0.00124766]]
1407 Cost: 0.0048070513 
Prediction:
 [[ 0.9775073 ]
 [ 0.81486976]
 [ 0.6164803 ]
 [ 0.33782098]
 [ 0.57517105]
 [ 0.54822147]
 [ 0.17211658]
 [-0.00123564]]
1408 Cost: 0.004806654 
Prediction:
 [[ 0.97751343]
 [ 0.81486905]
 [ 0.61647826]
 [ 0.33782545]
 [ 0.57516503]
 [ 0.54821587]
 [ 0.17210843]
 [-0.00122364]]
1409 Cost: 0.004806249 
Prediction:
 [[ 0.9775195 ]
 [ 0.81486833]
 [ 0.6164763 ]
 [ 0.33782995]
 [ 0.57515883]
 [ 0.54821026]
 [ 0.1721003 ]
 [-0.00121164]]
1410 Cost: 0.0048058517 
Prediction:
 [[ 0.97752553]
 [ 0.8148676 ]
 [ 0.6164743 ]
 [ 0.33783445]
 [ 0.5751528 ]
 [ 0.54820466]
 [ 0.17209218]
 [-0.00119964]]
1411 Cost: 0.004805455 
Prediction:
 [[ 0.9775318 

1688 Cost: 0.00470106 
Prediction:
 [[0.97908497]
 [0.8147142 ]
 [0.6160074 ]
 [0.33910716]
 [0.5736047 ]
 [0.54663724]
 [0.17000622]
 [0.00185529]]
1689 Cost: 0.004700704 
Prediction:
 [[0.9790902 ]
 [0.81471395]
 [0.616006  ]
 [0.3391118 ]
 [0.57359964]
 [0.54663163]
 [0.1699993 ]
 [0.00186535]]
1690 Cost: 0.004700345 
Prediction:
 [[0.9790954 ]
 [0.8147134 ]
 [0.61600465]
 [0.33911654]
 [0.5735945 ]
 [0.546626  ]
 [0.16999237]
 [0.00187539]]
1691 Cost: 0.0046999874 
Prediction:
 [[0.97910047]
 [0.81471306]
 [0.6160033 ]
 [0.33912122]
 [0.5735894 ]
 [0.54662025]
 [0.16998546]
 [0.00188541]]
1692 Cost: 0.0046996325 
Prediction:
 [[0.97910565]
 [0.8147126 ]
 [0.61600184]
 [0.33912578]
 [0.57358426]
 [0.5466145 ]
 [0.16997853]
 [0.00189542]]
1693 Cost: 0.0046992744 
Prediction:
 [[0.97911066]
 [0.81471217]
 [0.6160004 ]
 [0.33913046]
 [0.57357913]
 [0.54660875]
 [0.16997163]
 [0.00190544]]
1694 Cost: 0.004698918 
Prediction:
 [[0.9791157 ]
 [0.8147117 ]
 [0.6159991 ]
 [0.33913514]
 [0.5

1980 Cost: 0.0046017566 
Prediction:
 [[0.98044515]
 [0.814622  ]
 [0.6156724 ]
 [0.34048355]
 [0.5722221 ]
 [0.54495925]
 [0.16813642]
 [0.00453316]]
1981 Cost: 0.004601429 
Prediction:
 [[0.98044944]
 [0.81462187]
 [0.6156716 ]
 [0.34048826]
 [0.5722177 ]
 [0.5449534 ]
 [0.16813052]
 [0.00454149]]
1982 Cost: 0.0046011056 
Prediction:
 [[0.98045367]
 [0.81462145]
 [0.6156707 ]
 [0.34049302]
 [0.57221335]
 [0.54494756]
 [0.1681246 ]
 [0.00454983]]
1983 Cost: 0.004600784 
Prediction:
 [[0.98045784]
 [0.8146213 ]
 [0.61566967]
 [0.34049776]
 [0.572209  ]
 [0.5449418 ]
 [0.16811869]
 [0.00455816]]
1984 Cost: 0.0046004606 
Prediction:
 [[0.98046196]
 [0.8146209 ]
 [0.61566865]
 [0.3405025 ]
 [0.5722046 ]
 [0.54493594]
 [0.16811278]
 [0.00456649]]
1985 Cost: 0.0046001323 
Prediction:
 [[0.98046625]
 [0.81462085]
 [0.6156679 ]
 [0.3405073 ]
 [0.57220024]
 [0.5449301 ]
 [0.1681069 ]
 [0.00457484]]
1986 Cost: 0.0045998124 
Prediction:
 [[0.98047024]
 [0.8146206 ]
 [0.61566687]
 [0.34051204]
 [